const fs=require('fs');const SRC=process.argv[2]||process.env.PLANNER_SRC||'finance-planner.html';
const html=fs.readFileSync(SRC,'utf8');
const code=html.split('<script>')[1].split('</script>')[0];
const st=new Proxy({},{get:(t,k)=>(k==='style'||k==='dataset'||k==='classList')?new Proxy({},{get:()=>()=>{}}):()=>{},set:()=>true});
global.document={getElementById:()=>st,querySelectorAll:()=>[],querySelector:()=>null,addEventListener:()=>{},createElement:()=>st};
global.window={scrollTo:()=>{}};global.localStorage={getItem:()=>null,setItem:()=>{},removeItem:()=>{}};global.confirm=()=>false;global.Blob=class{};global.URL={createObjectURL:()=>'',revokeObjectURL:()=>{}};global.FileReader=class{};
eval(code+';global.X={S,cardModel,cardsview,expiringSoon,periodsOf,currentSlot};');
const X=global.X, m=X.cardModel();
let f=0;const chk=(l,g,w)=>{const ok=Math.abs(g-w)<0.01;if(!ok)f++;console.log((ok?'  PASS ':'  FAIL '),l.padEnd(40),g.toFixed(2).padStart(10),'expect',w.toFixed(2));};

console.log('--- annual value per card ---');
m.cards.forEach(c=>console.log('  '+c.name.padEnd(26), 'fee', String(c.fee).padStart(4), '| credits', c.total.toFixed(2).padStart(9), '| slots', c.credits.length));
console.log('--- Amex Platinum credit math ---');
const p=m.cards[0];
chk('Uber Cash (11x15 + 35)', p.credits[0].total, 11*15+35);
chk('Digital ent (12x25)', p.credits[1].total, 300);
chk('Walmart+ (12x12.95)', p.credits[2].total, 155.40);
chk('Resy (4x100)', p.credits[3].total, 400);
chk('lululemon (4x75)', p.credits[4].total, 300);
chk('Hotel (2x300)', p.credits[5].total, 600);
chk('Platinum total', p.total, 200+300+155.40+400+300+600+200+219+300+200+120);
console.log('--- United Quest rideshare Dec override ---');
const q=m.cards[3], rs=q.credits.find(c=>c.n==='Rideshare');
chk('rideshare (11x8 + 12)', rs.total, 11*8+12);
console.log('--- slot shapes ---');
[['monthly',12],['quarterly',4],['semi',2],['annual',1]].forEach(([per,n])=>{
  const got=X.periodsOf({period:per,amt:10}).length;
  const ok=got===n; if(!ok)f++;
  console.log((ok?'  PASS ':'  FAIL '),per.padEnd(12),got,'slots, expect',n);
});
console.log('--- toggle behaviour ---');
const before=X.cardModel().totalUsed;
X.S.cardUse['amexplat:0:Aug']=true;
const after=X.cardModel().totalUsed;
chk('marking Aug Uber adds $15', after-before, 15);
const cur=X.cardModel().cards[0].credits[0];
console.log('   Uber Cash: used', cur.used, '| missed', cur.missed, '| open now', cur.openNow, '| pct', (cur.pctUsed*100).toFixed(1)+'%');
delete X.S.cardUse['amexplat:0:Aug'];
console.log('--- expiring soon (today is Aug 12) ---');
X.expiringSoon().slice(0,6).forEach(x=>console.log('   '+String(x.days).padStart(3)+'d  '+('$'+x.amt).padStart(6)+'  '+x.credit.padEnd(28)+x.card));
console.log('--- totals ---');
console.log('   available', m.totalAvailable.toFixed(2), '| fees', m.totalFees.toFixed(2), '| open now', m.totalOpen.toFixed(2));
const v=X.cardsview();
console.log('   view', v.length, 'bytes,', ['undefined','NaN','[object Object]'].filter(x=>v.includes(x)).join(',')||'clean');
console.log(f===0?'\n>>> ALL CHECKS PASSED':'\n>>> '+f+' FAILURES');
